# 创建user表

CREATE TABLE IF NOT EXISTS user(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30) NOT NULL UNIQUE,
password VARCHAR(50) NOT NULL,
createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

# 新建用户
INSERT INTO user (name,`password`) VALUES("admin",'123');

# 查询用户是否注册过
SELECT * FROM user WHERE name=?;
-- 测试
SELECT * FROM user WHERE name='admin';
